/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
 /*\title Capture of PWM signal via GPT12
 * \abstract The GPT12 unit is used to capture an external PWM signal and calculate the PWM frequency.
 * \description GPT12 timers are configured in capture mode. The data from the captured PWM signal is used to calculate
 *              the PWM frequency in software. The frequency is then stored in a variable.
 *
 * \name GPT12_PWM_Capture_1_KIT_TC275_LK
 * \version V1.0.0
 * \board AURIX TC275 lite Kit, KIT_AURIX_TC275_LITE, TC27xTP_D-Step
 * \keywords GPT12, PWM, timer, frequency, capture, AURIX, GPT12_PWM_Capture_1
 * \documents https://www.infineon.com/aurix-expert-training/Infineon-AURIX_GPT12_PWM_Capture_1_KIT_TC275_LK-TR-v01_00_00-EN.pdf
 * \documents https://www.infineon.com/aurix-expert-training/TC27D_iLLD_UM_1_0_1_12_0.chm
 * \lastUpdated 2021-06-29
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "GPT12_PWM_Capture.h"
#include "ASCLIN_UART.h"

IfxCpu_syncEvent g_cpuSyncEvent = 0;
uint32 finalCntVal_main = 0;
float32 T3_frequency_main = 0.0;

//과제
uint32  g_cntOverflow_main = 0;
uint32  g_previousCntVal_main = 0;
uint32  currentCntVal_main = 0;
uint32  elaps_cnt_val = 0;
uint32 obs_distance =0;
int obs_dis_int =0;
float32 obs_float_distance =0.0;
int core0_main(void)
{
    init_ASCLIN_UART();                 /* Initialize the module                  */
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    /* Initialize the GPT module */
    init_GPT12_module();

    while(1)
    {
        finalCntVal_main;
        T3_frequency_main;

        //과제
        g_cntOverflow_main;
        g_previousCntVal_main;
        currentCntVal_main;

        elaps_cnt_val;

        generate_Sonar_Trig_signal();
        obs_float_distance;
        obs_dis_int =(int)obs_distance;
        send_sonar_data(obs_dis_int);
        //send_sonar_data(obs_distance);
    }
    return (1);
}
